name: Build Android APK (Docker)

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Disable BuildKit
        run: echo "DOCKER_BUILDKIT=0" >> $GITHUB_ENV

      - name: Build with Docker
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/app \
            -w /app \
            kivy/buildozer:stable \
            buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: CineStream-APK
          path: bin/*.apk
