name: Build Android APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Disable BuildKit (to avoid unsupported media type errors)
        run: |
          export DOCKER_BUILDKIT=0
          export COMPOSE_DOCKER_CLI_BUILD=0

      - name: Build with Docker
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/home/user/app \
            kivy/buildozer:latest \
            buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: my-android-apk
          path: bin/*.apk
